jedis:
  master:
    host: 192.168.116.12
    port: 6380
    MinIdle: 30
    MaxIdle: 300
    MaxTotal: 3000
    #获取连接时的最大等待毫秒数(如果设置为阻塞时BlockWhenExhausted),如果超时就抛异常, 小于零:阻塞不确定的时间,  默认-1
    MaxWaitMillis: 10000
    TestOnCreate: true
    TestOnReturn: true
    #在获取连接的时候检查有效性, 默认false
    TestOnBorrow: false
    #在空闲时检查有效性, 默认false
    TestWhileIdle: false
    #是否启用后进先出, 默认true
    Lifo: true
    #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
    BlockWhenExhausted: true
    #每次逐出检查时 逐出的最大数目 如果为负数就是 : 1/abs(n), 默认3
    NumTestsPerEvictionRun: 10
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    TimeBetweenEvictionRunsMillis: -1
    #逐出连接的最小空闲时间 默认1800000毫秒(30分钟)
    MinEvictableIdleTimeMillis: 1800000
    #对象空闲多久后逐出, 当空闲时间>该值 且 空闲连接>最大空闲数 时直接逐出,不再根据MinEvictableIdleTimeMillis判断  (默认逐出策略)   
    SoftMinEvictableIdleTimeMillis: 1800000
  # jedis cluster
  cluster:
    connectionTimeout: 5000
    soTimeout: 10000
    maxAttempts: 10
    password: dev